<h1>Checkpoint de disruptive</h1>

<h4>Nessa atividade iremos fazer um estudo elaborado do dataset</h4>



In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_table("/home/breast-cancer.data", delimiter = ",")
df.columns = ['target', 'age', 'menopause','tumor-size', 'inv-nodes', 'node-caps', 'deg-malig', 'breast', 'breast-quad', 'irradiant']

In [3]:
labels = df.target
labels.head()

0    no-recurrence-events
1    no-recurrence-events
2    no-recurrence-events
3    no-recurrence-events
4    no-recurrence-events
Name: target, dtype: object

In [4]:
df.replace('?', np.nan, inplace = True)
df

target    age menopause tumor-size inv-nodes node-caps  \
0    no-recurrence-events  40-49   premeno      20-24       0-2        no   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  60-69      ge40      15-19       0-2        no   
3    no-recurrence-events  40-49   premeno        0-4       0-2        no   
4    no-recurrence-events  60-69      ge40      15-19       0-2        no   
..                    ...    ...       ...        ...       ...       ...   
280     recurrence-events  30-39   premeno      30-34       0-2        no   
281     recurrence-events  30-39   premeno      20-24       0-2        no   
282     recurrence-events  60-69      ge40      20-24       0-2        no   
283     recurrence-events  40-49      ge40      30-34       3-5        no   
284     recurrence-events  50-59      ge40      30-34       3-5        no   

     deg-malig breast breast-quad irradiant  
0            2  right    right_up        no  
1            2   left    left_low        no  
2            2  right     left_up        no  
3            2  right   right_low        no  
4            2   left    left_low        no  
..         ...    ...         ...       ...  
280          2   left     left_up        no  
281          3   left     left_up       yes  
282          1  right     left_up        no  
283          3   left    left_low        no  
284          3   left    left_low        no  

[285 rows x 10 columns]

In [5]:
df.loc[pd.isna(df['node-caps']), 'node-caps'].shape[0]

8

In [6]:
df.isna().sum()

target         0
age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      8
deg-malig      0
breast         0
breast-quad    1
irradiant      0
dtype: int64

In [7]:
def calc_percentual_indefinido(dataframe, coluna):
  indefinidos = dataframe.loc[pd.isna(dataframe[coluna]), coluna].shape[0]
  total = dataframe[coluna].shape[0]

  return (indefinidos/total) * 100

In [8]:
calc_percentual_indefinido(df, 'node-caps')

2.807017543859649

In [9]:
calc_percentual_indefinido(df, 'breast-quad')

0.3508771929824561

In [10]:
data = df.dropna()

In [11]:
calc_percentual_indefinido(data, 'node-caps')

0.0

In [12]:
calc_percentual_indefinido(data, 'breast-quad')

0.0

In [13]:
def one_hot(categorias, valor):
  categorias = list(set(categorias))
  indice = categorias.index(valor)
  vetor = np.zeros(len(categorias))
  vetor[indice] = 1
  return vetor

In [14]:
data['node-caps']

0      no
1      no
2      no
3      no
4      no
       ..
280    no
281    no
282    no
283    no
284    no
Name: node-caps, Length: 276, dtype: object

In [15]:
one_hot(data['node-caps'], 'no')

array([1., 0.])

In [16]:
one_hot(data['tumor-size'], '25-29')

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
data['tumor-size'].unique()

array(['20-24', '15-19', '0-4', '25-29', '50-54', '10-14', '30-34',
       '40-44', '35-39', '5-9', '45-49'], dtype=object)

In [18]:
data['age'] = [ one_hot(data['age'], _) for _ in data['age'] ]
data['menopause'] = [ one_hot(data['menopause'], _) for _ in data['menopause'] ]
data['tumor-size'] = [ one_hot(data['tumor-size'], _) for _ in data['tumor-size'] ]
data['inv-nodes'] = [ one_hot(data['inv-nodes'], _) for _ in data['inv-nodes'] ]
data['node-caps'] = [ one_hot(data['node-caps'], _) for _ in data['node-caps'] ]
data['deg-malig'] = [ one_hot(data['deg-malig'], _) for _ in data['deg-malig'] ]
data['breast'] = [ one_hot(data['breast'], _) for _ in data['breast'] ]
data['breast-quad'] = [ one_hot(data['breast-quad'], _) for _ in data['breast-quad'] ]
data['irradiant'] = [ one_hot(data['irradiant'], _) for _ in data['irradiant'] ]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [19]:
data

target                             age        menopause  \
0    no-recurrence-events  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
1    no-recurrence-events  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
2    no-recurrence-events  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
3    no-recurrence-events  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
4    no-recurrence-events  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
..                    ...                             ...              ...   
280     recurrence-events  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
281     recurrence-events  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
282     recurrence-events  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
283     recurrence-events  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 0.0, 1.0]   
284     recurrence-events  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 1.0]   

                                            tumor-size  \
0    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
3    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
..                                                 ...   
280  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...   
281  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
282  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
283  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...   
284  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...   

                               inv-nodes   node-caps        deg-malig  \
0    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
1    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
2    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
3    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
4    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
..                                   ...         ...              ...   
280  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
281  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 0.0, 1.0]   
282  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [1.0, 0.0, 0.0]   
283  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 0.0, 1.0]   
284  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 0.0, 1.0]   

         breast                breast-quad   irradiant  
0    [0.0, 1.0]  [0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  
1    [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
2    [0.0, 1.0]  [0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0]  
3    [0.0, 1.0]  [0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0]  
4    [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
..          ...                        ...         ...  
280  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0]  
281  [1.0, 0.0]  [0.0, 1.0, 0.0, 0.0, 0.0]  [0.0, 1.0]  
282  [0.0, 1.0]  [0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0]  
283  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
284  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  

[276 rows x 10 columns]

In [20]:
data['target'] = [ one_hot(data['target'], _) for _ in data['target'] ]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [21]:
labels = data['target'].values

In [22]:
labels

array([array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), array([1., 0.]), array([1., 0.]), array([1., 0.]),
       array([1., 0.]), a

In [23]:
data = data.drop(['target'], axis = 1)
data.head(10)

age        menopause  \
0  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
1  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
2  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
3  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
4  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
5  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0, 0.0]   
6  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 1.0]   
7  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
8  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   
9  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0]   

                                          tumor-size  \
0  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...   
5  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
6  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
7  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
8  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
9  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...   

                             inv-nodes   node-caps        deg-malig  \
0  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
1  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
2  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
3  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
4  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
5  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
6  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [1.0, 0.0, 0.0]   
7  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
8  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 1.0, 0.0]   
9  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  [0.0, 0.0, 1.0]   

       breast                breast-quad   irradiant  
0  [0.0, 1.0]  [0.0, 0.0, 1.0, 0.0, 0.0]  [1.0, 0.0]  
1  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
2  [0.0, 1.0]  [0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0]  
3  [0.0, 1.0]  [0.0, 0.0, 0.0, 1.0, 0.0]  [1.0, 0.0]  
4  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
5  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
6  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
7  [1.0, 0.0]  [0.0, 0.0, 0.0, 0.0, 1.0]  [1.0, 0.0]  
8  [0.0, 1.0]  [0.0, 1.0, 0.0, 0.0, 0.0]  [1.0, 0.0]  
9  [1.0, 0.0]  [1.0, 0.0, 0.0, 0.0, 0.0]  [1.0, 0.0]

In [26]:
def vetorizar(age, menopause, tumorSize, invNodes, nodeCaps, degMalig, breast, breastQuad, irradiant):
  return age.tolist() + menopause.tolist() + tumorSize.tolist() + invNodes.tolist() + \
        nodeCaps.tolist() + degMalig.tolist() + breast.tolist() + breast.tolist() + breastQuad.tolist() + irradiant.tolist()

In [27]:
entrada = [vetorizar(*_) for _ in data.values]
entrada

[[0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0],
 [0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  0.0],
 [0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0],
 [0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1